#!/bin/bash      # This line is "Shebang" or "bang" line. It is absolute path of bash interpreter.
echo "###############################################################"
echo -e "\033[0;31m"
echo "Hostname: $(hostname)"
echo -e "\033[0;37m"
echo "###############################################################"
echo -e "\033[0;32m"
echo "IP: $(ifconfig ens160 | head -n2 | grep -v flags | cut -c14-29)"
echo -e "\033[0;37m"
echo "###############################################################"
echo -e "\033[0;33m"
echo "Working Directory: $(pwd)"
echo -e "\033[0;37m"
echo "###############################################################"

